'use client';

import React, { useState } from 'react';
import { X, Copy, Check, FileDown, ShieldAlert, Cpu } from 'lucide-react';
import { sounds } from '../../engine/soundFx';

export default function PostMortemModal({
  isOpen,
  onClose,
  nodes,
  defcon,
  riskScore,
  causalExplanation
}) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const criticalNodes = nodes.filter(n => n.status === 'critical');
  const driftingNodes = nodes.filter(n => n.status === 'drift' || n.status === 'quarantined');
  const now = new Date().toISOString();

  const reportMarkdown = `# INCIDENT POST-MORTEM REPORT // CASCADE-ZERO
**Generated At:** ${now}
**DEFCON Status:** DEFCON ${defcon}
**Horizon Risk Score:** ${riskScore}%
**Causal Horizon Summary:** ${causalExplanation}

---

## 1. Executive Summary
During the scheduled cutover horizon (T+10h target), autonomous topological telemetry detected cascading delay propagation across interdependent microservices.

- **Total Milestones In Horizon:** ${nodes.length}
- **Critical Threshold Breaches:** ${criticalNodes.length}
- **Causal Drift Active:** ${driftingNodes.length}

---

## 2. Root Cause Analysis
${causalExplanation}

### Milestone Impact Matrix:
${nodes.map(n => `- **[${n.id}] ${n.name}**: Slip +${n.effectiveSlipMinutes}m (SLA Buffer: ${n.slaBufferMinutes}m) · Risk: ${n.doomsdayScore}% · Status: ${n.status.toUpperCase()}`).join('\n')}

---

## 3. Corrective & Preventative Actions (Sanity Lake Governance)
1. **Automated Buffer Absorption:** Increase dynamic buffer on high-centrality dependencies.
2. **Causal Circuit Breakers:** Decouple non-essential settlement webhooks during cutover.
3. **Continuous Real-Time GROQ Watchers:** Subscribe to Sanity Lake live mutation streams.

---
*Report cryptographically generated by CASCADE-ZERO Autonomous War Room.*
`;

  const handleCopy = () => {
    sounds.playPing();
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-2xl max-h-[85vh] flex flex-col rounded-2xl border border-cyan-500/30 bg-slate-950 p-6 shadow-[0_0_50px_rgba(6,182,212,0.25)] text-slate-100 font-mono">
        <button
          onClick={() => {
            sounds.playClick();
            onClose();
          }}
          className="absolute top-4 right-4 p-1.5 rounded-lg border border-slate-800 hover:border-slate-600 bg-slate-900 text-slate-400 hover:text-slate-200 transition-all"
        >
          <X className="w-4 h-4" />
        </button>

        <div className="flex items-center gap-3 mb-4">
          <div className="p-2.5 rounded-xl border border-cyan-500/30 bg-cyan-950/40 text-cyan-400">
            <FileDown className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-sm font-black tracking-wide text-slate-100 uppercase">
              Incident Post-Mortem Generator
            </h3>
            <p className="text-[11px] text-slate-400">
              Deterministic causal post-mortem exported for engineering governance
            </p>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto rounded-xl border border-slate-800 bg-slate-900/60 p-4 text-xs text-slate-300 leading-relaxed font-mono whitespace-pre-wrap select-all">
          {reportMarkdown}
        </div>

        <div className="flex items-center justify-between pt-4 mt-4 border-t border-slate-800">
          <div className="text-[11px] text-slate-400">
            Export ready in GitHub Flavored Markdown
          </div>

          <div className="flex gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-4 py-2 rounded-lg border border-cyan-500/40 hover:border-cyan-400 bg-cyan-950 hover:bg-cyan-900 text-xs text-cyan-300 font-bold transition-all shadow-[0_0_15px_rgba(6,182,212,0.2)]"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied to Clipboard!' : 'Copy Markdown Report'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
