'use client';

import React, { useState } from 'react';
import confetti from 'canvas-confetti';
import {
  FileText,
  CheckCircle2,
  Clock,
  ShieldCheck,
  Rocket,
  Users,
  Copy,
  Check,
  ArrowRight,
  Eye,
  GitCommit,
  User,
  X,
  Sparkles,
  ExternalLink
} from 'lucide-react';
import { sounds } from '../../engine/soundFx';

export default function GovernancePage() {
  const [activeStage, setActiveStage] = useState(3);
  const [copied, setCopied] = useState(false);
  const [showToast, setShowToast] = useState(false);
  const [showAuditModal, setShowAuditModal] = useState(false);
  const [showCutoverModal, setShowCutoverModal] = useState(false);
  const [cutoverProgress, setCutoverProgress] = useState(0);
  const [isCutoverRunning, setIsCutoverRunning] = useState(false);
  const [cutoverComplete, setCutoverComplete] = useState(false);

  const [approvals, setApprovals] = useState({
    chen: true,
    patel: true,
    nakamura: false
  });

  const markdownContent = `# Incident Post-Mortem: Causal Drift in Payment Routing
**Incident ID:** INC-2025-0417
**Date:** April 17, 2025

## Executive Summary
A causal drift in payment routing logic led to intermittent 504s for 18 minutes, affecting ~0.82% of transactions. No data loss or financial inconsistency.

## Timeline
• 09:12:03 Drift detected in causal simulation (deviation > 3σ)
• 09:14:47 Alert escalated to on-call.
• 09:19:02 Rollback initiated.
• 09:30:11 Traffic restored to baseline.

## Root Cause
Routing weight update did not account for downstream latency distribution shift introduced in v0.7.1.

## Resolution
Rollback to v0.7.0 and added latency-distribution guardrail.

## Impact
• Affected: 2,341 transactions
• Failed: 19 (0.82%)
• Duration: 18m 8s
---
Generated by CASCADE // ZERO Incident Intelligence`;

  const approvedCount = Object.values(approvals).filter(Boolean).length;
  const allApproved = approvedCount === 3;

  const handleCopy = () => {
    sounds.playPing();
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setShowToast(true);
    setTimeout(() => setCopied(false), 2200);
    setTimeout(() => setShowToast(false), 3000);
  };

  const toggleApproval = (key) => {
    sounds.playClick();
    setApprovals(prev => {
      const next = { ...prev, [key]: !prev[key] };
      const nextCount = Object.values(next).filter(Boolean).length;
      if (nextCount === 3) {
        sounds.playChime();
        setActiveStage(4);
      }
      return next;
    });
  };

  const handleStartCutover = () => {
    sounds.playPing();
    setIsCutoverRunning(true);
    setCutoverProgress(15);

    setTimeout(() => setCutoverProgress(45), 600);
    setTimeout(() => setCutoverProgress(75), 1300);
    setTimeout(() => {
      setCutoverProgress(100);
      setIsCutoverRunning(false);
      setCutoverComplete(true);
      setActiveStage(5);
      sounds.playChime();
      confetti({
        particleCount: 120,
        spread: 90,
        origin: { y: 0.6 },
        colors: ['#10b981', '#34d399', '#059669', '#6ee7b7']
      });
    }, 2000);
  };

  const stages = [
    { number: '01', title: 'Draft Spec', icon: <FileText className="w-4 h-4 text-emerald-400" /> },
    { number: '02', title: 'Causal Simulation', icon: <GitCommit className="w-4 h-4 text-emerald-400" /> },
    { number: '03', title: 'Peer Review', icon: <Users className="w-4 h-4 text-emerald-400" /> },
    { number: '04', title: 'Approval', icon: <ShieldCheck className="w-4 h-4 text-emerald-400" /> },
    { number: '05', title: 'Live Cutover', icon: <Rocket className="w-4 h-4 text-emerald-400" /> }
  ];

  return (
    <div className="flex-1 max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-5 flex flex-col gap-5 relative">
      
      {/* Toast Notification */}
      {showToast && (
        <div className="fixed top-16 right-6 z-50 flex items-center gap-2 px-4 py-2.5 rounded-xl border border-emerald-500/60 bg-slate-900/95 text-emerald-300 font-mono text-xs shadow-[0_0_25px_rgba(16,185,129,0.4)] animate-in fade-in slide-in-from-top-3 duration-200">
          <CheckCircle2 className="w-4 h-4 text-emerald-400" />
          <span>Post-Mortem markdown copied to clipboard!</span>
        </div>
      )}

      {/* Title Header */}
      <div>
        <h1 className="text-2xl sm:text-3xl font-black text-slate-100 tracking-tight font-sans">
          Governance
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 font-sans mt-0.5">
          Structured control. Predictable outcomes.
        </p>
      </div>

      {/* 5-Stage Stepper Bar matching exact reference image ref_gov_stepper.png */}
      <div className="w-full overflow-x-auto pb-2 sm:pb-0">
        <div className="flex items-center min-w-[760px] sm:min-w-0 justify-between">
          {stages.map((stage, idx) => {
            const stepNum = idx + 1;
            const isCompleted = stepNum < activeStage || (stepNum === 3 && allApproved) || (stepNum === 4 && allApproved && cutoverComplete);
            const isCurrent = stepNum === activeStage && !cutoverComplete;
            const isLineActive = (idx + 1) <= activeStage || (idx === 2 && allApproved);

            return (
              <React.Fragment key={stage.number}>
                {/* Stage Card */}
                <div
                  onClick={() => {
                    sounds.playClick();
                    setActiveStage(stepNum);
                  }}
                  className={`cursor-pointer rounded-2xl p-4 transition-all duration-300 border flex-1 max-w-[210px] select-none h-[110px] flex flex-col justify-between ${
                    isCurrent && stepNum === 3
                      ? 'border-emerald-400 bg-[#071813] shadow-[0_0_24px_rgba(16,185,129,0.32)] ring-1 ring-emerald-400/80 scale-[1.02]'
                      : isCurrent
                      ? 'border-emerald-400 bg-emerald-950/30 shadow-[0_0_20px_rgba(16,185,129,0.25)] ring-1 ring-emerald-400/80'
                      : isCompleted
                      ? 'border-emerald-500/40 bg-[#07110f]/90 hover:border-emerald-400/60'
                      : 'border-slate-800 bg-[#070d0c] opacity-80 hover:opacity-100 hover:border-slate-700'
                  }`}
                >
                  {/* Top row: 03 with Avatar ring for Step 3, or normal number */}
                  {stepNum === 3 ? (
                    <div className="flex items-center gap-2.5">
                      <div className="w-7 h-7 rounded-full border border-emerald-400/90 bg-emerald-950/80 flex items-center justify-center text-emerald-400 shadow-[0_0_10px_rgba(16,185,129,0.5)] shrink-0">
                        <User className="w-3.5 h-3.5" />
                      </div>
                      <div className="text-xs font-mono font-bold text-emerald-400">
                        {stage.number}
                      </div>
                    </div>
                  ) : (
                    <div className="text-xs font-mono text-slate-400">
                      {stage.number}
                    </div>
                  )}

                  <h3 className="text-xs sm:text-sm font-bold text-slate-100 truncate font-sans">
                    {stage.title}
                  </h3>

                  <div className="flex items-center gap-1.5 text-[11px] font-mono">
                    {isCompleted ? (
                      <span className="text-emerald-400 font-semibold flex items-center gap-1.5">
                        {stage.icon}
                        Completed ✓
                      </span>
                    ) : isCurrent ? (
                      <span className="text-emerald-300 font-bold flex items-center gap-1.5">
                        <Users className="w-3.5 h-3.5 text-emerald-400" />
                        In Progress
                      </span>
                    ) : (
                      <span className="text-slate-500 flex items-center gap-1.5">
                        {stage.icon}
                        Pending
                      </span>
                    )}
                  </div>
                </div>

                {/* Connecting Line between cards with green dot (NO lines through text) */}
                {idx < stages.length - 1 && (
                  <div className="flex items-center px-1.5 sm:px-2 flex-shrink-0 w-8 sm:w-12 lg:w-16">
                    <div
                      className={`h-[2px] w-full transition-all duration-300 ${
                        isLineActive
                          ? 'bg-emerald-400 shadow-[0_0_8px_#10b981]'
                          : 'bg-slate-800'
                      }`}
                    />
                    <div
                      className={`w-2 h-2 rounded-full shrink-0 -ml-1 transition-all duration-300 ${
                        isLineActive
                          ? 'bg-emerald-400 shadow-[0_0_8px_#10b981]'
                          : 'bg-slate-700'
                      }`}
                    />
                  </div>
                )}
              </React.Fragment>
            );
          })}
        </div>
      </div>

      {/* Large Centerpiece: Post-Mortem Generator (matching Image 1) */}
      <div className="rounded-2xl border border-slate-800/90 bg-[#070b13]/95 shadow-2xl p-6 relative overflow-hidden">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-800/80 mb-5">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-emerald-400" />
            <h2 className="text-sm sm:text-base font-mono font-bold text-slate-100">
              Post-Mortem Generator
            </h2>
          </div>

          <span className="px-3 py-1 rounded-full border border-emerald-500/40 bg-emerald-950/40 text-emerald-400 font-mono text-[10px] tracking-wider uppercase">
            Generated from incident data
          </span>
        </div>

        {/* 2-Column Split: Markdown Preview & One-Click Copy */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-center">
          
          {/* Left Preview Box (8 cols) */}
          <div className="lg:col-span-8 rounded-xl border border-slate-800 bg-slate-950/90 p-4 font-mono text-xs text-slate-300 leading-relaxed max-h-[320px] overflow-y-auto">
            <div className="flex items-center gap-1.5 text-[10px] text-slate-500 uppercase tracking-wider mb-2.5 pb-1 border-b border-slate-900">
              <Eye className="w-3.5 h-3.5 text-emerald-400" />
              <span>Markdown Preview</span>
            </div>
            <pre className="whitespace-pre-wrap">{markdownContent}</pre>
          </div>

          {/* Right One-Click Copy Box (4 cols) matching Image 1 */}
          <div className="lg:col-span-4 flex flex-col items-center text-center p-6 rounded-xl border border-slate-800/80 bg-slate-900/40">
            {/* Glowing Emerald Document Icon */}
            <div className="w-16 h-16 rounded-full border border-emerald-400 bg-emerald-950/60 shadow-[0_0_25px_rgba(16,185,129,0.35)] flex items-center justify-center text-emerald-400 mb-4">
              <FileText className="w-8 h-8" />
            </div>

            <h3 className="text-base font-bold text-slate-100 mb-1.5 font-sans">
              One-click post-incident reports.
            </h3>

            <p className="text-xs text-slate-400 leading-relaxed mb-6 font-sans">
              Auto-assembled from causal simulations, logs, and approvals.
            </p>

            <button
              onClick={handleCopy}
              className="w-full max-w-[200px] flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-mono font-bold text-xs transition-all shadow-[0_0_20px_rgba(16,185,129,0.4)] cursor-pointer active:scale-95"
            >
              {copied ? <Check className="w-4 h-4 text-slate-950" /> : <Copy className="w-4 h-4 text-slate-950" />}
              <span>{copied ? 'Copied!' : 'Copy'}</span>
            </button>
          </div>

        </div>

      </div>

      {/* Bottom Row: Audit Trail & Approval Status (matching Image 1) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
        
        {/* Left: Audit Trail (6 cols) */}
        <div className="lg:col-span-6 rounded-2xl border border-slate-800/90 bg-[#070b13]/95 shadow-2xl p-5">
          <div className="flex items-center justify-between pb-3 border-b border-slate-800/80 mb-4">
            <div className="flex items-center gap-2 text-xs font-mono font-bold text-slate-200">
              <Clock className="w-4 h-4 text-emerald-400" />
              <span>Audit Trail</span>
            </div>
            <button
              onClick={() => {
                sounds.playClick();
                setShowAuditModal(true);
              }}
              className="text-[11px] font-mono text-emerald-400 hover:underline cursor-pointer"
            >
              View all
            </button>
          </div>

          <div className="space-y-3 font-mono text-xs">
            <div className="flex items-start gap-3">
              <span className="w-2 h-2 rounded-full bg-emerald-400 mt-1.5 shrink-0 shadow-[0_0_6px_#10b981]" />
              <div className="flex-1">
                <div className="flex items-center justify-between text-slate-200">
                  <span className="font-semibold">Causal Simulation completed</span>
                  <span className="text-[10px] text-slate-500">09:14:47</span>
                </div>
                <div className="text-[10px] text-slate-500 font-sans">System</div>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <span className="w-2 h-2 rounded-full bg-emerald-400 mt-1.5 shrink-0 shadow-[0_0_6px_#10b981]" />
              <div className="flex-1">
                <div className="flex items-center justify-between text-slate-200">
                  <span className="font-semibold">Peer review submitted by A. Chen</span>
                  <span className="text-[10px] text-slate-500">09:16:22</span>
                </div>
                <div className="text-[10px] text-slate-500 font-sans">Peer Review</div>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <span className="w-2 h-2 rounded-full bg-emerald-400 mt-1.5 shrink-0 shadow-[0_0_6px_#10b981]" />
              <div className="flex-1">
                <div className="flex items-center justify-between text-slate-200">
                  <span className="font-semibold">Approval requested</span>
                  <span className="text-[10px] text-slate-500">09:18:05</span>
                </div>
                <div className="text-[10px] text-slate-500 font-sans">System</div>
              </div>
            </div>
          </div>
        </div>

        {/* Right: Approval Status (6 cols) */}
        <div className="lg:col-span-6 rounded-2xl border border-slate-800/90 bg-[#070b13]/95 shadow-2xl p-5">
          <div className="flex items-center justify-between pb-3 border-b border-slate-800/80 mb-4">
            <div className="flex items-center gap-2 text-xs font-mono font-bold text-slate-200">
              <ShieldCheck className="w-4 h-4 text-emerald-400" />
              <span>Approval Status</span>
            </div>
            
            {allApproved ? (
              <button
                id="btn-execute-cutover"
                onClick={() => {
                  sounds.playClick();
                  setShowCutoverModal(true);
                }}
                className="text-[11px] font-mono text-emerald-400 hover:text-emerald-300 font-bold flex items-center gap-1 cursor-pointer animate-pulse"
              >
                <span>Execute Cutover →</span>
              </button>
            ) : (
              <span className="text-[11px] font-mono text-slate-500">
                View details
              </span>
            )}
          </div>

          <div className="mb-4">
            <div className="text-xs font-mono text-slate-300 mb-0.5">
              {allApproved ? 'All required sign-offs granted' : 'Waiting for approval'}
            </div>
            <div className="text-[11px] font-mono text-slate-500">
              {approvedCount} of 3 required approvals
            </div>
          </div>

          {/* 3 Interactive Reviewers matching Image 1 */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs font-mono">
            
            {/* Reviewer 1: A. Chen */}
            <div
              id="reviewer-chen"
              onClick={() => toggleApproval('chen')}
              className={`p-2.5 rounded-xl border flex items-center justify-between transition-all cursor-pointer ${
                approvals.chen
                  ? 'border-emerald-500/40 bg-emerald-950/20 text-slate-200 hover:border-emerald-400'
                  : 'border-slate-800 bg-slate-900/40 text-slate-400 hover:border-slate-700'
              }`}
            >
              <div>
                <div className="font-bold text-[11px] flex items-center gap-1">
                  <User className="w-3 h-3 text-emerald-400" />
                  <span>A. Chen</span>
                </div>
                <div className="text-[9px] text-slate-500 font-sans">Engineering Lead</div>
              </div>
              <div className={`w-4 h-4 rounded-full border flex items-center justify-center text-[10px] ${
                approvals.chen ? 'border-emerald-400 bg-emerald-500 text-slate-950 font-bold' : 'border-slate-600'
              }`}>
                {approvals.chen && '✓'}
              </div>
            </div>

            {/* Reviewer 2: M. Patel */}
            <div
              id="reviewer-patel"
              onClick={() => toggleApproval('patel')}
              className={`p-2.5 rounded-xl border flex items-center justify-between transition-all cursor-pointer ${
                approvals.patel
                  ? 'border-emerald-500/40 bg-emerald-950/20 text-slate-200 hover:border-emerald-400'
                  : 'border-slate-800 bg-slate-900/40 text-slate-400 hover:border-slate-700'
              }`}
            >
              <div>
                <div className="font-bold text-[11px] flex items-center gap-1">
                  <span className="w-2.5 h-2.5 rounded-full border border-slate-500" />
                  <span>M. Patel</span>
                </div>
                <div className="text-[9px] text-slate-500 font-sans">Platform Architect</div>
              </div>
              <div className={`w-4 h-4 rounded-full border flex items-center justify-center text-[10px] ${
                approvals.patel ? 'border-emerald-400 bg-emerald-500 text-slate-950 font-bold' : 'border-slate-600'
              }`}>
                {approvals.patel && '✓'}
              </div>
            </div>

            {/* Reviewer 3: R. Nakamura */}
            <div
              id="reviewer-nakamura"
              onClick={() => toggleApproval('nakamura')}
              className={`p-2.5 rounded-xl border flex items-center justify-between transition-all cursor-pointer ${
                approvals.nakamura
                  ? 'border-emerald-500/40 bg-emerald-950/20 text-slate-200 hover:border-emerald-400'
                  : 'border-slate-800 bg-slate-900/40 text-slate-400 hover:border-emerald-500/50'
              }`}
            >
              <div>
                <div className="font-bold text-[11px] flex items-center gap-1">
                  <span className="w-2.5 h-2.5 rounded-full border border-slate-500" />
                  <span>R. Nakamura</span>
                </div>
                <div className="text-[9px] text-slate-500 font-sans">Risk Officer</div>
              </div>
              <div className={`w-4 h-4 rounded-full border flex items-center justify-center text-[10px] ${
                approvals.nakamura ? 'border-emerald-400 bg-emerald-500 text-slate-950 font-bold' : 'border-slate-600'
              }`}>
                {approvals.nakamura && '✓'}
              </div>
            </div>

          </div>
        </div>

      </div>

      {/* Audit Trail Modal */}
      {showAuditModal && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="w-full max-w-xl rounded-2xl border border-slate-800 bg-[#070b13] p-6 shadow-2xl relative animate-in fade-in zoom-in-95 duration-200">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800 mb-4">
              <h3 className="text-base font-mono font-bold text-slate-100 flex items-center gap-2">
                <Clock className="w-4 h-4 text-emerald-400" />
                <span>FULL INCIDENT AUDIT TRAIL</span>
              </h3>
              <button
                onClick={() => setShowAuditModal(false)}
                className="p-1 rounded-lg border border-slate-800 hover:border-slate-700 text-slate-400"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="space-y-3 font-mono text-xs max-h-[300px] overflow-y-auto">
              <div className="p-2.5 rounded-lg bg-slate-900/60 border border-slate-800">
                <div className="flex justify-between text-slate-200 font-semibold mb-0.5">
                  <span>Advisory Lock Release Verified</span>
                  <span className="text-[10px] text-slate-500">09:32:00</span>
                </div>
                <div className="text-[10px] text-emerald-400">Postgres Aurora Node • System Auto-Agent</div>
              </div>
              <div className="p-2.5 rounded-lg bg-slate-900/60 border border-slate-800">
                <div className="flex justify-between text-slate-200 font-semibold mb-0.5">
                  <span>Traffic Restored to Baseline</span>
                  <span className="text-[10px] text-slate-500">09:30:11</span>
                </div>
                <div className="text-[10px] text-emerald-400">Edge Proxy • Routing Supervisor</div>
              </div>
              <div className="p-2.5 rounded-lg bg-slate-900/60 border border-slate-800">
                <div className="flex justify-between text-slate-200 font-semibold mb-0.5">
                  <span>Rollback Initiated to v0.7.0</span>
                  <span className="text-[10px] text-slate-500">09:19:02</span>
                </div>
                <div className="text-[10px] text-indigo-400">CI/CD Canary Dispatcher</div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Live Cutover Deployment Modal */}
      {showCutoverModal && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="w-full max-w-lg rounded-2xl border border-emerald-500/50 bg-[#070b13] p-6 shadow-2xl relative animate-in fade-in zoom-in-95 duration-200">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800 mb-4">
              <h3 className="text-base font-mono font-bold text-slate-100 flex items-center gap-2">
                <Rocket className="w-5 h-5 text-emerald-400" />
                <span>STAGE 05: LIVE CUTOVER DEPLOYMENT</span>
              </h3>
              <button
                onClick={() => setShowCutoverModal(false)}
                className="p-1 rounded-lg border border-slate-800 hover:border-slate-700 text-slate-400"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <p className="text-xs text-slate-300 font-sans mb-4">
              All 3 reviewer approvals verified. Ready to initiate canary blue-green cutover for release horizon v0.7.2.
            </p>

            {/* Progress Bar */}
            <div className="w-full bg-slate-800 rounded-full h-2 mb-2 overflow-hidden">
              <div
                className="bg-emerald-400 h-full transition-all duration-300 shadow-[0_0_12px_#10b981]"
                style={{ width: `${cutoverProgress}%` }}
              />
            </div>

            <div className="flex justify-between text-[11px] font-mono text-slate-400 mb-5">
              <span>{isCutoverRunning ? 'Shifting production traffic...' : cutoverComplete ? 'Cutover Complete' : 'Awaiting trigger'}</span>
              <span className="text-emerald-400 font-bold">{cutoverProgress}%</span>
            </div>

            <div className="flex justify-end gap-3">
              <button
                onClick={() => setShowCutoverModal(false)}
                className="px-4 py-2 rounded-xl border border-slate-800 text-slate-400 font-mono text-xs"
              >
                Close
              </button>

              <button
                id="btn-start-safe-cutover"
                onClick={handleStartCutover}
                disabled={isCutoverRunning || cutoverComplete}
                className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-mono font-bold text-xs shadow-[0_0_20px_rgba(16,185,129,0.4)] disabled:opacity-50 cursor-pointer"
              >
                <Rocket className="w-4 h-4" />
                <span>{isCutoverRunning ? 'Deploying...' : cutoverComplete ? 'Cutover Live ✓' : 'Execute Cutover'}</span>
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
